# Generated by Django 3.2.25 on 2025-07-08 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_type', models.CharField(choices=[('daily_reflection', 'Daily Reflection'), ('mood_awareness', 'Mood Awareness'), ('activity_tracking', 'Activity Tracking')], default='daily_reflection', max_length=20)),
                ('stake', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('coin_balance', models.IntegerField(default=0)),
                ('clarity_score', models.PositiveSmallIntegerField(default=100)),
                ('streak_count', models.PositiveSmallIntegerField(default=0)),
                ('last_mood_log', models.DateField(blank=True, null=True)),
                ('streak_last_updated', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nudge_type', models.CharField(choices=[('mood_trend', 'Mood Trend Alert'), ('time_reminder', 'Time-based Reminder'), ('skip_pattern', 'Skip Pattern Alert'), ('streak_motivation', 'Streak Motivation')], max_length=20)),
                ('message', models.TextField()),
                ('tone', models.CharField(choices=[('gen_z', 'Gen Z'), ('professional', 'Professional')], max_length=12)),
                ('viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='tracker.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('activities', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood',
                'verbose_name_plural': 'Moods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn_mood', 'Mood Log (+1)'), ('earn_reflection', 'Reflection (+2)'), ('earn_feedback', 'AI Feedback (+1)'), ('lose_inactive', 'Inactivity Penalty (-1)'), ('stake_challenge', 'Challenge Stake'), ('win_challenge', 'Challenge Win'), ('lose_challenge', 'Challenge Loss'), ('spend_insight', 'Deep Insight Purchase')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.challenge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='tracker.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='tracker.profile'),
        ),
        migrations.CreateModel(
            name='AISuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(max_length=32)),
                ('suggestion_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
