# Generated by Django 3.2.25 on 2025-07-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Mild'), (4, 'Moderate'), (5, 'Good'), (6, 'High'), (7, 'Very High'), (8, 'Intense'), (9, 'Very Intense'), (10, 'Extreme')], default=5),
        ),
    ]
