# Generated by Django 5.2 on 2025-07-08 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_behavior_engine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={},
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.challenge'),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('daily_reflection', 'Daily Reflection'), ('mood_awareness', 'Mood Awareness'), ('activity_tracking', 'Activity Tracking')], default='daily_reflection', max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='stake',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='tracker.profile'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn_mood', 'Mood Log (+1)'), ('earn_reflection', 'Reflection (+2)'), ('earn_feedback', 'AI Feedback (+1)'), ('lose_inactive', 'Inactivity Penalty (-1)'), ('stake_challenge', 'Challenge Stake'), ('win_challenge', 'Challenge Win'), ('lose_challenge', 'Challenge Loss'), ('spend_insight', 'Deep Insight Purchase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='nudge_type',
            field=models.CharField(choices=[('mood_trend', 'Mood Trend Alert'), ('time_reminder', 'Time-based Reminder'), ('skip_pattern', 'Skip Pattern Alert'), ('streak_motivation', 'Streak Motivation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nudge',
            name='tone',
            field=models.CharField(choices=[('gen_z', 'Gen Z'), ('professional', 'Professional')], max_length=12),
        ),
    ]
