# Generated by Django 5.1.2 on 2025-05-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_mood_activities_mood_rating_comment_moodcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodComment',
        ),
    ]
