# Generated by Django 3.2.25 on 2025-05-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_profile'),
        ('tracker', '0003_delete_moodcomment'),
    ]

    operations = [
    ]
