#!/bin/bash
# Deploy AI Service to Render - Helper Script

echo "🤖 MoodSync AI Service Deployment Helper"
echo "========================================"

echo ""
echo "📋 Prerequisites Check:"
echo "1. ✅ GitHub repository connected to Render"
echo "2. ✅ Gemini API key ready"
echo "3. ✅ Render account set up"

echo ""
echo "🚀 Deployment Steps:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Select your GitHub repository"
echo "4. Configure as follows:"
echo ""
echo "   Service Name: moodsync-ai-service"
echo "   Root Directory: ai_service"
echo "   Environment: Python 3"
echo "   Build Command: pip install -r requirements.txt"
echo "   Start Command: python app.py"
echo ""
echo "5. Add Environment Variables:"
echo "   GEMINI_API_KEY=your-actual-gemini-api-key"
echo "   PORT=10000"
echo "   FLASK_ENV=production"
echo ""
echo "6. Deploy!"
echo ""
echo "⏱️  Deployment takes 3-5 minutes"
echo ""
echo "🔗 After deployment, update main app environment:"
echo "   AI_SERVICE_URL=https://moodsync-ai-service.onrender.com"
echo ""
echo "✅ Test endpoints:"
echo "   - GET /api/suggestions/motivation/"
echo "   - GET /api/suggestions/habits/"
echo "   - GET /api/insights/"
echo ""
echo "📊 Monitor in app logs for 'personalized_with_ai': true"
echo ""
echo "Need help? Check docs/AI_SERVICE_DEPLOYMENT.md"
