# Generated by Django 5.1.2 on 2024-10-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
