# Generated by Django 5.1.2 on 2024-10-16 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_mood_mood_alter_mood_sentiment_alter_mood_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='notes',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
