# Generated by Django 5.1.2 on 2024-10-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_mood_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='sentiment',
            field=models.CharField(default='neutral', choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad')], max_length=10),
        ),
    ]
