# Generated by Django 5.1.2 on 2024-10-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_mood_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='sentiment',
            field=models.CharField(choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad')], max_length=10),
        ),
    ]
